# Generated by Django 3.1.7 on 2021-02-27 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-date'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
