# Generated by Django 3.1.7 on 2021-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0002_auto_20210227_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsection',
            name='type',
            field=models.CharField(
                choices=[('ACADEMIC', 'Academic'), ('GUILD', "Students' Guild"), ('SOCIAL', 'Social'),
                         ('WELLBEING', 'Wellbeing')], default='ACADEMIC', max_length=20),
            preserve_default=False,
        ),
    ]
