# Generated by Django 3.1.7 on 2021-03-06 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0003_forumsection_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumsection',
            old_name='type',
            new_name='category',
        ),
    ]
