# Generated by Django 3.1.7 on 2021-03-06 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0004_auto_20210306_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeForumThread',
        ),
    ]
