# Generated by Django 3.1.7 on 2021-03-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0005_delete_collegeforumthread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date & time posted'),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='body',
            field=models.TextField(verbose_name='reply body'),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date & time posted'),
        ),
    ]
